# Chapter 2 Prelimiaries

In [1]:
from d2l import torch as d2l

In [2]:
import torch

In [4]:
x = torch.arange(12, dtype=torch.float32)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [5]:
x.numel()

12

In [7]:
x.shape

torch.Size([12])

In [8]:
X = x.reshape(3, 4)
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [12]:
Y = x.reshape(-1, 4)
Y

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [13]:
Z = x.reshape(3, -1)
Z

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [15]:
X = torch.zeros((2, 3, 4))
X

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [16]:
torch.ones((4, 3, 2))

tensor([[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]])

In [18]:
# Create a tensor with elements drawn from 
# a standard Gaussian(normal) distribution 
# with mean 0 and standard deviation 1.

torch.rand(3, 4)

tensor([[0.1008, 0.7066, 0.6447, 0.1720],
        [0.3240, 0.6484, 0.5930, 0.0292],
        [0.2713, 0.5787, 0.8519, 0.1225]])

In [20]:
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

In [4]:
!pip install jax jaxlib

  Obtaining dependency information for jaxlib from https://files.pythonhosted.org/packages/c3/7b/9de4634dcf8590cf68245aead7336f499aab92f4b9e0c4efb4271692be12/jaxlib-0.4.25-cp39-cp39-macosx_10_14_x86_64.whl.metadata
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 83.3/83.3 MB 11.3 MB/s eta 0:00:0000:0100:01


In [1]:
import jax
from jax import numpy as jnp

RuntimeError: This version of jaxlib was built using AVX instructions, which your CPU and/or operating system do not support. You may be able work around this issue by building jaxlib from source.